url: "http://JosephSchiarizzi.com"
name: Joseph Schiarizzi
description: "My name is Joseph Schiarizzi.  I like to hack stuff and try out new technology.  Twitter and Github are great ways to keep up with me!"
language: en-us

author: Joseph Schiarizzi
email: Joseph@JosephSchiarizzi.com

permalink: /:year/:month/:title/

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions

exclude:
  - CNAME
  - Gemfile
  - LICENSE.txt
  - README.md

google:
  analytics:
    profile: "none"

disqus:
  shortname: disqus_EUcfthsC7O

twitter:
  username: CupOJoseph


